// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TitanicPredictor_MachineLearning
{
    public partial class TitanicAuto_NoCabinNumber
    {
        /// <summary>
        /// model input class for TitanicAuto_NoCabinNumber.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Pclass")]
            public float Pclass { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Title")]
            public string Title { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Sex")]
            public string Sex { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Family")]
            public float Family { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Fare")]
            public float Fare { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Embarked")]
            public string Embarked { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Survived")]
            public bool Survived { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TitanicAuto_NoCabinNumber.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Pclass")]
            public float Pclass { get; set; }

            [ColumnName(@"Title")]
            public float[] Title { get; set; }

            [ColumnName(@"Sex")]
            public float[] Sex { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Family")]
            public float Family { get; set; }

            [ColumnName(@"Fare")]
            public float Fare { get; set; }

            [ColumnName(@"Embarked")]
            public float[] Embarked { get; set; }

            [ColumnName(@"Survived")]
            public bool Survived { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TitanicAuto-NoCabinNumber.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
